name: flutter_bloc_boilerplate
description: "A Flutter Bloc boilerplate project with authentication, themes, and multi-language support."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  http: ^1.4.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  quickalert: ^1.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
